name: Update MAU & TOTAL badges
permissions: { contents: write }

on:
  schedule:
   - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  calc-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p badges

      - id: mau
        run: echo "value=$(curl -s https://jellyfin-stats.queukat.workers.dev/mau)" >> $GITHUB_OUTPUT
      - id: total
        run: echo "value=$(curl -s https://jellyfin-stats.queukat.workers.dev/total)" >> $GITHUB_OUTPUT

      - uses: emibcn/badge-action@v2
        with: { label: active users, status: ${{ steps.mau.outputs.value }}, color: blue, path: badges/mau.svg }
      - uses: emibcn/badge-action@v2
        with: { label: total users,  status: ${{ steps.total.outputs.value }}, color: 9cf,  path: badges/total.svg }

      - uses: EndBug/add-and-commit@v9
        with:
          add: 'badges/*.svg'
          message: 'chore: update MAU & TOTAL badges'
